### PR TITLE
Container

### PR DESCRIPTION
**Pull request by LaneEcho**
- moved logic out of header into main container
- created main container component
- refactored header to be presentational component
- main container renders header and flow components

### CODE REVIEW

**Review by domc13 — APPROVED** [review]
great work today!

**Review by R-Griggs — APPROVED** [review]
Looks Good.

**Review by mgnchoi — APPROVED** [review]
looks good!

**Review by dev-cameron — APPROVED** [review]
Excellentt work here, lets talk about architecture next.

**Comment by R-Griggs** [comment]
Parapets and flying buttresses?

**Pull request merged**
